name: thiess
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff2f1d'
    - '#8baaa8'
    - '#fff2f2'
    - '#dc0f16'
    - '#ff847b'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
