name: thiess
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#009514'
    - '#00cc21'
    - '#29fa39'
    - '#cdfece'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
